import React, { createContext, useState, useContext, useEffect, useCallback } from 'react';
import { WalletOutlined, CheckCircleFilled, CreditCardOutlined } from '@ant-design/icons';
import { apiClient } from '../api/apiClient';

const GlobalContext = createContext({});

// No more mock data. Completely API driven.



export const GlobalProvider = ({ children }) => {
  const [searchValue, setSearchValue] = useState("");
  const [totalGates, setTotalGates] = useState(6);
  const [activeLocation, setActiveLocation] = useState("toan-he-thong");
  const [isEmergency, setIsEmergency] = useState(false); // Persistent emergency state

  // User and Shift Tracking (Initially Empty/Loading)
  const [currentUser, setCurrentUser] = useState({ name: "Đang tải...", id: "", station: "", avatar: "", shift: "" });
  const [shiftHistory, setShiftHistory] = useState([]);

  // Data States (Initially Empty)
  const [transactions, setTransactions] = useState([]);
  const [activityLogs, setActivityLogs] = useState([]);
  const [activeVehicles, setActiveVehicles] = useState([]);
  const [currentVehicle, setCurrentVehicle] = useState(null);
  const [recentlyProcessed, setRecentlyProcessed] = useState([]); // [{plate, action}] // Hide plates temporarily to prevent flashing
  
  // Security Alerts & Stats (Initially Empty)
  const [securityAlerts, setSecurityAlerts] = useState([
    {
      id: 'AL-BL-' + Date.now(),
      plate: '51F-888.88',
      type: 'BIỂN SỐ ĐEN',
      reason: 'Xe bị báo mất cắp, có yêu cầu giữ xe từ cơ quan chức năng.',
      time: new Date().toLocaleTimeString('vi-VN', { hour: '2-digit', minute: '2-digit' }),
      status: 'new',
      isManual: true
    },
    {
      id: 'AL-TH-' + Date.now(),
      plate: '30G-123.45',
      type: 'NGHI NGỜ TRỘM CẮP',
      reason: 'Phát hiện chấn động mạnh khi xe đang bật Khóa chống trộm.',
      time: new Date().toLocaleTimeString('vi-VN', { hour: '2-digit', minute: '2-digit' }),
      status: 'new',
      isManual: true
    }
  ]);
  const [vehicleFines, setVehicleFines] = useState([]); // Array of fines: { id, plate, amount, reason, date }
  const [shiftStats, setShiftStats] = useState({ revenue: 0, cash: 0, transfer: 0, transactions: 0 });
  const [dailyVolume, setDailyVolume] = useState(0);

  // CENTRALIZED FETCH FUNCTION
  const fetchAllDataFromBackend = useCallback(async () => {
    try {
      // 1. Fetch Logs
      let fetchedLogsData = [];
      try {
        const logsData = await apiClient.get('/logs');
        if (logsData && logsData.items && logsData.items.length > 0) {
          fetchedLogsData = logsData.items;
          setActivityLogs(prev => {
            const manualLogs = prev.filter(log => log.isManual);
            const fetchedLogs = logsData.items.filter(fetched => !manualLogs.some(m => m.plate === fetched.plate && Math.abs(new Date(m.time).getTime() - new Date(fetched.time).getTime()) < 15000));
            return [...fetchedLogs, ...manualLogs].sort((a, b) => new Date(b.time) - new Date(a.time));
          });
          
          // Auto-generate security alerts from warning logs
          const warningLogs = logsData.items.filter(l => l.status === 'Cảnh báo' || l.status === 'Cảnh Báo' || l.status === 'Warning' || l.status === 'Lỗi thẻ' || l.status === 'Lỗi' || l.status === 'ERROR');
          if (warningLogs.length > 0) {
            setSecurityAlerts(prev => {
              let newAlerts = [...prev];
              let added = false;
              warningLogs.forEach(log => {
                const alertId = `alert-log-${log.id || log.plate}-${log.time}`;
                if (!newAlerts.some(a => a.id === alertId)) {
                    // Format time string
                    let formattedTime = log.time;
                    try {
                      const d = new Date(log.time);
                      if (!isNaN(d.getTime())) {
                        formattedTime = d.toLocaleTimeString('vi-VN', { hour: '2-digit', minute: '2-digit' }) + ' ' + d.toLocaleDateString('vi-VN', { day: '2-digit', month: '2-digit' });
                      }
                    } catch (e) {}

                    newAlerts.unshift({
                      id: alertId,
                      type: log.status.includes('Lỗi') || log.status === 'ERROR' ? 'HỆ THỐNG LỖI' : 'CẢNH BÁO LPR',
                      plate: log.plate,
                      reason: `Ghi nhận ${log.action} tại ${log.gate} với trạng thái: ${log.status}`,
                      time: formattedTime,
                      isAutoGenerated: true
                    });
                  added = true;
                }
              });
              return added ? newAlerts : prev;
            });
          }
        }
      } catch (e) {
        console.error("Failed to fetch logs", e);
      }

      // 2. Fetch Transactions
      try {
        const txnData = await apiClient.get(`/revenue/transactions?_t=${new Date().getTime()}`);
        if (txnData && txnData.items && txnData.items.length > 0) {
          setTransactions(prev => {
            const manualTxns = prev.filter(t => t.isManual);
            const fetchedTxns = txnData.items.filter(fetched => !manualTxns.some(m => m.id === fetched.id));
            return [...fetchedTxns, ...manualTxns].sort((a, b) => new Date(b.timestamp) - new Date(a.timestamp));
          });
        }
      } catch (e) {
        console.error("Failed to fetch transactions", e);
      }
      
      // 3. Fetch Shifts
      try {
        import('../services/shiftService').then(module => {
          module.shiftService.getShifts().then(data => {
            if (data && data.length > 0) {
              const mapped = data.map(d => ({
                id: d.id, staff: d.staffName, shift: d.shiftType, 
                start: new Date(d.startTime).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'}),
                end: d.endTime ? new Date(d.endTime).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'}) : "--:--",
                vehicles: d.vehiclesHandled || 0, status: d.status, isCurrent: d.isCurrent
              }));
              setShiftHistory(mapped);
            } else {
              setShiftHistory([]);
            }
          }).catch(() => setShiftHistory([]));
        });
      } catch (e) {
        console.error("Failed to fetch shifts", e);
      }

      // 4. Fetch Active Vehicles (Sessions without checkout)
      try {
        const sessionData = await apiClient.get('/sessions');
        
        let dataArray = [];
        if (Array.isArray(sessionData)) {
          dataArray = sessionData;
        } else if (sessionData && Array.isArray(sessionData.content)) {
          dataArray = sessionData.content;
        } else if (sessionData && Array.isArray(sessionData.items)) {
          dataArray = sessionData.items;
        } else if (sessionData && Array.isArray(sessionData.data)) {
          dataArray = sessionData.data;
        }

        if (dataArray && dataArray.length >= 0) {
          const active = dataArray
            .filter(s => ['ACTIVE', 'PASSED_CONFIRMED'].includes(s.sessionStatus))
            .map((session, index) => {
              const checkInTime = session.checkInTime ? new Date(session.checkInTime) : null;
              let durationStr = "Đang vào";
              if (checkInTime && !isNaN(checkInTime.getTime())) {
                const diffMs = Date.now() - checkInTime.getTime();
                const hours = Math.floor(diffMs / (1000 * 60 * 60));
                const minutes = Math.floor((diffMs % (1000 * 60 * 60)) / (1000 * 60));
                durationStr = `${hours}h ${minutes}m`;
              }
                const carImages = [
                  "https://images.unsplash.com/photo-1573348722427-f1d6819fdf98?auto=format&fit=crop&w=600&q=80",
                  "https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=600&q=80",
                  "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=600&q=80",
                  "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=600&q=80",
                  "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=600&q=80",
                  "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=600&q=80",
                  "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=600&q=80",
                  "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=600&q=80"
                ];
                const charSum = (session.licensePlate || "A").split('').reduce((sum, char) => sum + char.charCodeAt(0), 0);
                const uniqueImage = carImages[charSum % carImages.length];

              const zoneCode = session.assignedZoneCode || session.assignedZoneId || "";
              const mapZoneToFloor = (code) => {
                if (!code) return "Chưa gán";
                const c = code.toUpperCase();
                if (c === "F1") return "Tầng 1";
                if (c === "F2") return "Tầng 2";
                if (c === "B1") return "Tầng B1";
                if (c === "G") return "Tầng G";
                return c;
              };

              const isPendingSession = session.isPending === true;
              const sessionIsVip = session.isVip || session.vip;
              const isMobilePrepaid = session.sessionStatus === 'PASSED_CONFIRMED';

              return {
                id: session.id,
                plate: session.licensePlate || "Không rõ",
                type: sessionIsVip ? "VIP" : "Vãng lai",
                isVip: sessionIsVip,
                confidence: "99%",
                status: isMobilePrepaid ? "Đã thanh toán lưu động" : ((session.isSuspicious || session.suspicious) ? "Lỗi thẻ" : (session.exitGate && !sessionIsVip ? "Chờ thanh toán" : "Hợp lệ")),
                gate: isPendingSession ? (session.exitGate || session.entryGate || null) : (session.exitGate || null),
                entryGate: session.entryGate || null,
                exitGate: session.exitGate || null,
                sessionStatus: session.sessionStatus,
                inTime: checkInTime && !isNaN(checkInTime.getTime()) ? checkInTime.toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'}) : "--:--",
                timestamp: checkInTime ? checkInTime.getTime() : 0,
                outTime: "--:--",
                image: session.mobileCheckoutPhoto || uniqueImage,
                model: session.vehicleModel || session.vehicleBrand || "Chưa xác định",
                duration: durationStr,
                assignedZoneCode: zoneCode,
                floorName: mapZoneToFloor(zoneCode),
                vehicleType: session.vehicleType || session.vehicleSize || null,
                cardCode: session.cardCode
              };
            });

          setRecentlyProcessed(rp => {
            const exitPlates = rp.filter(r => r.action === 'exit').map(r => r.plate);
            const entryPlates = rp.filter(r => r.action === 'entry').map(r => r.plate);
            
            let newActive = active.filter(v => !exitPlates.includes(v.plate));
            newActive = newActive.map(v => entryPlates.includes(v.plate) ? { ...v, gate: null } : v);
            
            setActiveVehicles(newActive.sort((a, b) => b.timestamp - a.timestamp));
            return rp;
          });
        } else {
          setActiveVehicles([]);
        }
      } catch (e) {
        console.error("Failed to fetch sessions for active vehicles", e);
        setActiveVehicles([]);
      } 
      
      // 5. Fetch Current User Profile
      try {
        const userProfile = await apiClient.get('/auth/me');
        setCurrentUser(userProfile);
      } catch (e) {
        console.error("Failed to fetch user profile", e);
        setCurrentUser({ name: "Chưa đăng nhập", id: "N/A", station: "N/A", avatar: "", shift: "N/A" });
      }

      // 6. Fetch Security Alerts
      try {
        const alerts = await apiClient.get('/security/alerts');
        if (alerts) {
          setSecurityAlerts(prev => {
            const manualAlerts = prev.filter(alert => alert.isManual || alert.isAutoGenerated);
            const fetchedAlerts = (Array.isArray(alerts) ? alerts : (alerts.items || [])).filter(fetched => !manualAlerts.some(m => m.id === fetched.id));
            return [...manualAlerts, ...fetchedAlerts];
          });
        } else {
          setSecurityAlerts(prev => prev.filter(alert => alert.isManual || alert.isAutoGenerated));
        }
      } catch (e) {
        console.error("Failed to fetch security alerts", e);
        setSecurityAlerts(prev => prev.filter(alert => alert.isManual || alert.isAutoGenerated));
      }

      // 7. Fetch Shift Stats
      try {
        const stats = await apiClient.get('/revenue/shift-stats');
        setShiftStats(stats || { revenue: 0, cash: 0, transfer: 0, transactions: 0 });
      } catch (e) {
        console.error("Failed to fetch shift stats", e);
        setShiftStats({ revenue: 0, cash: 0, transfer: 0, transactions: 0 });
      }

      // 8. Fetch Daily Volume
      try {
        const volume = await apiClient.get('/sessions/daily-volume');
        setDailyVolume(volume?.volume || 0);
      } catch (e) {
        console.error("Failed to fetch daily volume", e);
        setDailyVolume(0);
      }

      // 9. Fetch System Settings
      try {
        const settings = await apiClient.get('/settings/system');
        if (settings?.totalGates) {
          setTotalGates(parseInt(settings.totalGates, 10));
        }
      } catch (e) {
        console.error("Failed to fetch settings", e);
      }

    } catch (error) {
      console.error("Failed to fetch backend data", error);
    }
  }, []);

  // Use fetchAllDataFromBackend in useEffect
  useEffect(() => {
    fetchAllDataFromBackend();
    const interval = setInterval(fetchAllDataFromBackend, 3000);
    return () => clearInterval(interval);
  }, [fetchAllDataFromBackend]);

  // Actions
  const addTransaction = (newTx) => setTransactions(prev => [{ ...newTx, isManual: true }, ...prev]);
  const addActivityLog = (newLog) => setActivityLogs(prev => [{ ...newLog, isManual: true, id: Math.random().toString() }, ...prev]);
  const addSecurityAlert = (newAlert) => setSecurityAlerts(prev => [{ ...newAlert, isManual: true }, ...prev]);
  const removeSecurityAlert = (id) => setSecurityAlerts(prev => prev.filter(alert => alert.id !== id));
  
  const addVehicleFine = (fine) => setVehicleFines(prev => [...prev, { ...fine, id: Math.random().toString(), date: new Date().toISOString() }]);
  const clearVehicleFines = (plate) => setVehicleFines(prev => prev.filter(f => f.plate !== plate));
  const getVehicleFines = (plate) => vehicleFines.filter(f => f.plate === plate);

  const restoreSecurityAlerts = () => {
    const mockBlacklist = {
      id: 'AL-BL-' + Date.now(),
      plate: '51F-888.88',
      type: 'BIỂN SỐ ĐEN',
      reason: 'Xe bị báo mất cắp, có yêu cầu giữ xe từ cơ quan chức năng.',
      time: new Date().toLocaleTimeString('vi-VN', { hour: '2-digit', minute: '2-digit' }),
      status: 'new',
      isManual: true
    };

    const mockTheft = {
      id: 'AL-TH-' + Date.now(),
      plate: '30G-123.45',
      type: 'NGHI NGỜ TRỘM CẮP',
      reason: 'Phát hiện chấn động mạnh khi xe đang bật Khóa chống trộm.',
      time: new Date().toLocaleTimeString('vi-VN', { hour: '2-digit', minute: '2-digit' }),
      status: 'new',
      isManual: true
    };

    setSecurityAlerts(prev => [mockBlacklist, mockTheft, ...prev]);
    fetchAllDataFromBackend();
  };

  const updateShiftStats = (amount, isCash = true) => {
    setShiftStats(prev => ({
      ...prev,
      revenue: prev.revenue + amount,
      cash: isCash ? prev.cash + amount : prev.cash,
      transfer: !isCash ? prev.transfer + amount : prev.transfer,
      transactions: prev.transactions + 1
    }));
  };

  const removeActiveVehicle = (plate) => {
    setActiveVehicles(prev => prev.filter(v => v.plate !== plate));
    
    // Temporarily hide this plate from subsequent API fetches for 15 seconds
    setRecentlyProcessed(prev => [...prev, { plate, action: 'exit' }]);
    setTimeout(() => {
      setRecentlyProcessed(prev => prev.filter(p => p.plate !== plate));
    }, 15000);

    if (currentVehicle?.plate === plate) {
      setCurrentVehicle(null);
    }
  };

  const processEntryVehicle = (plate) => {
    // Keep it in activeVehicles but clear its gate so it moves to "Trong bãi"
    setActiveVehicles(prev => prev.map(v => 
      v.plate === plate ? { ...v, gate: null, inTime: new Date().toLocaleTimeString('vi-VN', { hour: '2-digit', minute: '2-digit' }) } : v
    ));
    
    // Force API to keep its gate as null for 15s to give backend time to update
    setRecentlyProcessed(prev => [...prev, { plate, action: 'entry' }]);
    setTimeout(() => {
      setRecentlyProcessed(prev => prev.filter(p => p.plate !== plate));
    }, 15000);

    if (currentVehicle?.plate === plate) {
      setCurrentVehicle(null);
    }
  };

  const addActiveVehicle = (newVehicle) => {
    setActiveVehicles(prev => {
      if (prev.find(v => v.plate === newVehicle.plate)) return prev;
      return [newVehicle, ...prev];
    });
  };

  const INITIAL_GATES = [
    { id: 'L-VÀO 1', type: 'TRỐNG', typeColor: 'bg-slate-100 text-slate-400', plate: '---', barrier: 'ĐÓNG', barrierColor: 'text-red-500', mode: 'Tự động', actions: ['lock', 'wrench'], vehicleId: null },
    { id: 'L-VÀO 2', type: 'TRỐNG', typeColor: 'bg-slate-100 text-slate-400', plate: '---', barrier: 'ĐÓNG', barrierColor: 'text-red-500', mode: 'Tự động', actions: ['lock', 'wrench'], vehicleId: null },
    { id: 'L-VÀO 3', type: 'TRỐNG', typeColor: 'bg-slate-100 text-slate-400', plate: '---', barrier: 'ĐÓNG', barrierColor: 'text-red-500', mode: 'Tự động', actions: ['lock', 'wrench'], vehicleId: null },
    { id: 'L-RA 1', type: 'TRỐNG', typeColor: 'bg-slate-100 text-slate-400', plate: '---', barrier: 'ĐÓNG', barrierColor: 'text-red-500', mode: 'Tự động', actions: ['lock', 'wrench'], vehicleId: null },
    { id: 'L-RA 2', type: 'TRỐNG', typeColor: 'bg-slate-100 text-slate-400', plate: '---', barrier: 'ĐÓNG', barrierColor: 'text-red-500', mode: 'Tự động', actions: ['lock', 'wrench'], vehicleId: null },
    { id: 'L-RA 3', type: 'TRỐNG', typeColor: 'bg-slate-100 text-slate-400', plate: '---', barrier: 'ĐÓNG', barrierColor: 'text-red-500', mode: 'Tự động', actions: ['lock', 'wrench'], vehicleId: null }
  ];
  
  const [gates, setGates] = useState(INITIAL_GATES);
  const [gateLogs, setGateLogs] = useState([]); 

  useEffect(() => {
    setGates(prevGates => {
      let newGates = prevGates.map(g => {
        if (g.mode === 'Bảo trì') return g;
        return { ...g, type: 'TRỐNG', typeColor: 'bg-slate-100 text-slate-400', plate: '---', barrier: 'ĐÓNG', barrierColor: 'text-red-500', mode: 'Tự động', actions: ['lock', 'wrench'], vehicleId: null };
      });
      
      if (activeVehicles && activeVehicles.length > 0) {
        activeVehicles.filter(v => v.gate).forEach(v => {
          let rawGate = v.gate.toUpperCase();
          let gateId = rawGate;
          if (rawGate.includes('BỐT GÁC') || rawGate.includes('TRỰC 1')) {
            gateId = 'L-VÀO 1';
          } else {
            gateId = rawGate.replace(/CỔNG\s*[-]?\s*/g, 'L-');
          }
          let gateIndex = newGates.findIndex(g => g.id === gateId);
          if (gateIndex === -1) {
            newGates.push({ id: gateId, mode: 'Tự động' });
            gateIndex = newGates.length - 1;
          }
          let g = newGates[gateIndex];
          if (g.mode === 'Bảo trì') return;
          
          g.type = v.type.toUpperCase();
          g.typeColor = v.type === 'VIP' ? 'bg-slate-800 text-white' : 'bg-blue-100 text-blue-700';
          g.plate = v.plate;
          
          const isEntryGate = gateId.includes('VÀO');
          const isExitGate = gateId.includes('RA');
          if (isEntryGate) {
            // Entry gate: vehicle waits for staff approval
            g.mode = 'Thủ công';
            g.barrier = 'ĐANG CHỜ';
            g.barrierColor = 'text-yellow-600 bg-yellow-100 px-2 py-0.5 rounded';
            g.actions = ["approve", "reject"];
          } else if (isExitGate) {
            // Exit gate always waits for the staff payment/review flow.
            g.mode = 'Thủ công';
            g.barrier = 'ĐANG CHỜ';
            g.barrierColor = 'text-yellow-600 bg-yellow-100 px-2 py-0.5 rounded';
            g.actions = ["approve", "reject"];
          } else if (v.status === 'Cảnh báo' || v.status === 'Lỗi thẻ') {
            g.mode = 'Tự động';
            g.barrier = 'ĐÓNG';
            g.barrierColor = 'text-red-500';
            g.actions = ["lock", "wrench"];
          } else {
            g.mode = 'Tự động';
            g.barrier = 'MỞ';
            g.barrierColor = 'text-emerald-500';
            g.actions = ["lock", "wrench"];
          }
          g.vehicleId = v.id;
        });
      }
      return newGates;
    });
  }, [activeVehicles]);

  return (
    <GlobalContext.Provider value={{        searchValue, setSearchValue, activeLocation, setActiveLocation, totalGates, setTotalGates,
        isEmergency, setIsEmergency,
      currentUser, setCurrentUser, shiftHistory, setShiftHistory,
      transactions, addTransaction,
      activityLogs, addActivityLog,
      securityAlerts, addSecurityAlert, removeSecurityAlert, restoreSecurityAlerts,
      vehicleFines, addVehicleFine, clearVehicleFines, getVehicleFines,
      shiftStats, updateShiftStats, setShiftStats,
      dailyVolume, setDailyVolume,
      activeVehicles, currentVehicle, setCurrentVehicle, removeActiveVehicle, addActiveVehicle,
      gates, setGates, gateLogs, setGateLogs,
      fetchAllDataFromBackend, processEntryVehicle
    }}>
      {children}
    </GlobalContext.Provider>
  );
};

export const useGlobalContext = () => useContext(GlobalContext);
