# Database Configuration for Production
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Flyway Migration Validation
spring.flyway.validate-on-migrate=true

# JWT Configuration (15 Minutes Expiration for Prod)
app.jwtSecret=${JWT_SECRET}
app.jwtExpirationMs=900000

# VNPay Credentials
vnp.hashsecret=${VNP_HASH_SECRET}

# MoMo Credentials
momo.secret-key=${MOMO_SECRET_KEY}
momo.access-key=${MOMO_ACCESS_KEY}
