spring.datasource.url=jdbc:postgresql://localhost:5433/parking_db
spring.datasource.username=parking_user
spring.datasource.password=ParkingDB@2024!
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080


# JWT Configuration (Ghi chú phải nằm riêng một dòng như thế này)
app.jwtSecret=ChangeThisSecretToAStrongValueSuperLongKeyForSWP391ParkingProject2026Compliant
app.jwtExpirationMs=900000
app.refreshExpirationSec=604800000
