<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>check</name>
   <tag></tag>
   <elementGuidId>8fe99f2b-b0d9-4e90-94df-7fe6544e2f93</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>true</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <katalonVersion>11.2.1</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path>/api/blacklisted-cards/check/{cardId}</path>
   <restRequestMethod>GET</restRequestMethod>
   <restUrl>http://localhost:8080/api/blacklisted-cards/check/${cardId}</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>null</defaultValue>
      <description>&lt;string> {Required} null</description>
      <id>e7407d0b-f525-4e85-a8a7-0efc5ed69e01</id>
      <masked>false</masked>
      <name>cardId</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
